<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><?php echo $page->title; ?></title>
		<script src="<?php echo $config->urls->templates . 'assets/dist/scripts/scripts.bundle.js';?>"></script>
		<script src="<?php echo $config->urls->templates . 'assets/dist/scripts/styles.bundle.js';?>"></script>
		<script src="<?php echo $config->urls->templates . 'assets/dist/scripts/vendors.bundle.js';?>"></script>
	</head>
	<body>
		<main>
		